- name: default value
  hosts: localhost
  tasks:
  - name: print default value 
    ansible.builtin.debug:
     msg: "Hello {{Course | default ('Ansible') }}"


- name: uppre case # if we chang a number in upper case
  hosts: localhost
  vars: 
    greeting: "Hello, Good Morning"
  tasks: 
  - name: convert  into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case # if we chang a number in upper case
  hosts: localhost
  vars: 
    greeting: "Hello, Good Morning"
  tasks: 
  - name: convert  into lower
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [ 1,2,3,3,4,2,4,2,5,7,8,1,13,4,5,5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
     

- name: print min and max
  hosts: localhost
  vars:
    ages: [3,5,45,14,23,34,32,54,67,76]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"


- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs.
      Course: Ansbile
      Trainer: Sivakumar
      Duration: 120hr
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"